export const routes = {
  landing: '/',
  home: '/app',
  login: '/entrar',
  onboarding: '/comecar',
  ranking: '/ranking',
  locations: '/locais',
  locationsMine: '/locais?filtro=meus',
  locationsFavorites: '/locais?filtro=favoritos',
  locationsEnabled: '/locais?filtro=previsoes',
  locationNew: '/locais/novo',
  locationDetails: (locationId: string) => `/locais/${locationId}`,
  locationEdit: (locationId: string) => `/locais/${locationId}/editar`,
  account: '/conta',
  accountPreferences: '/conta/preferencias',
  accountNotifications: '/conta/notificacoes',
  premium: '/premium',
  diary: '/diario',
  about: '/sobre',
  partners: '/parceiros',
  partnerDetails: (slug: string) => `/parceiros/${slug}`,
  admin: '/admin',
  adminAudit: '/admin/auditoria',
  adminSpots: '/admin/locais',
  adminOfficialSpots: '/admin/locais-sistema',
  adminOfficialSpotNew: '/admin/locais-sistema/novo',
  adminOfficialSpotEdit: (locationId: string) => `/admin/locais-sistema/${locationId}`,
  adminUsers: '/admin/usuarios',
  adminPlans: '/admin/planos',
  adminPartners: '/admin/parceiros',
  adminPartnerNew: '/admin/parceiros/novo',
  adminPartnerEdit: (slug: string) => `/admin/parceiros/${slug}`,
} as const;
