export const routes = {
  home: '/',
  login: '/entrar',
  ranking: '/ranking',
  locations: '/locais',
  locationsMine: '/locais?filtro=meus',
  locationsFavorites: '/locais?filtro=favoritos',
  locationNew: '/locais/novo',
  locationDetails: (locationId: string) => `/locais/${locationId}`,
  locationEdit: (locationId: string) => `/locais/${locationId}/editar`,
  account: '/conta',
  about: '/sobre',
  partners: '/parceiros',
  partnerDetails: (slug: string) => `/parceiros/${slug}`,
  admin: '/admin',
  adminSpots: '/admin/locais',
  adminUsers: '/admin/usuarios',
  adminPartners: '/admin/parceiros',
  adminPartnerNew: '/admin/parceiros/novo',
  adminPartnerEdit: (slug: string) => `/admin/parceiros/${slug}`,
} as const;
